name: eyehelper
description: A new Flutter project.
version: 1.0.5+9

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  fl_chart: 0.45.0 # Charts library for statistics screen
  #flare_dart: 2.2.2
  flare_flutter: 3.0.2 # Animation
  firebase_core: 1.20.0
  firebase_crashlytics: 2.8.6 # Handle errors and send to cloud
  firebase_analytics: 9.1.2
  #flutter_statusbarcolor: 0.2.3 # Animation
  flutter_swiper: 1.1.6 # Swipe on main screen
  flutter_local_notifications: 9.7.0 # Notification
  flutter_time_picker_spinner: 2.0.0 # Notifications time picker
  #logger: 0.7.0 # Print beautiful logs
  path_provider: 2.0.11 # Notifications Sound
  shared_preferences: 2.0.15 # Statistic and notification
  share_plus: 4.0.10
  tuple: 2.0.0 # Extended data structure
  url_launcher: 6.1.5 #to go in AppStore
  flutter_vibrate: 1.3.0 # For vibrating while doing excercises.
  flutter_native_timezone: 2.0.0
  auto_size_text: 3.0.0
  permission_handler: 8.3.0
  app_review: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.2

flutter_icons:
  image_path_android: "assets/app_icons/ic_launcher.png"
  image_path_ios: "assets/app_icons/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/app_icons/ic_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/app_icons/ic_foreground.png" # only available for Android 8.0 devices and above

flutter:
  assets:
    - assets/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fira_sans_regular.ttf
          weight: 500
        - asset: assets/fira_sans_light.ttf
          weight: 200
  uses-material-design: true
