name: eyehelper
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  flutter_localizations:
    sdk: flutter
  fl_chart: 0.4.2 # Charts library for statistics screen
  flare_dart: 2.2.2
  flare_flutter: 1.6.2 # Animation
  flutter_statusbarcolor: 0.2.3 # Animation
  flutter_swiper: 1.1.4 # Swipe on main screen
  flutter_local_notifications: 0.8.0 # Notification
  flutter_time_picker_spinner: 1.0.5 # Notifications time picker
  logger: 0.7.0 # Print beautiful logs
  path_provider: 1.6.0 # Notifications Sound
  shared_preferences: 0.5.3 # Statistic and notification
  share: 0.6.2 #for sharing the app
  tuple: 1.0.2 # Extended data structure
  url_launcher: 5.1.4 #to go in AppStore
  vibration: 1.1.0 # For vibrating while doing excercises.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fira_sans_regular.ttf
          weight: 500
        - asset: assets/fira_sans_light.ttf
          weight: 200
  uses-material-design: true
