name: eyehelper
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  flutter_localizations:
    sdk: flutter
  flare_flutter: 1.3.0 # Animation
  flutter_swiper: 1.1.4 # Swipe on main screen
  flutter_local_notifications: 0.5.2 # Notification
  path_provider: 0.4.1 # Notifications Sound
  shared_preferences: 0.4.3 # Statistic and notification
  flutter_screenutil: 0.5.1 #For adaptive scaling on different screen sizes

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true