name: eyehelper
description: A new Flutter project.
version: 1.0.5+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  flutter_localizations:
    sdk: flutter
  fl_chart: 0.4.2 # Charts library for statistics screen
  flare_dart: 2.2.2
  flare_flutter: 1.6.2 # Animation
  firebase_core: 0.7.0
  firebase_crashlytics: 0.4.0 # Handle errors and send to cloud
  firebase_analytics: 7.0.1
  flutter_statusbarcolor: 0.2.3 # Animation
  flutter_swiper: 1.1.4 # Swipe on main screen
  flutter_local_notifications: 2.0.1+1 # Notification
  flutter_time_picker_spinner: 1.0.5 # Notifications time picker
  logger: 0.7.0 # Print beautiful logs
  path_provider: 1.6.0 # Notifications Sound
  shared_preferences: 0.5.3 # Statistic and notification
  share: 0.6.2 #for sharing the app
  tuple: 1.0.2 # Extended data structure
  url_launcher: 5.5.0 #to go in AppStore
  vibration: 1.1.0 # For vibrating while doing excercises.
  flutter_native_timezone: 1.0.4
  flutter_slidable: 0.5.7
  auto_size_text: "any"
  permission_handler: ^5.0.1+1
  app_review: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.7.4

flutter_icons:
  image_path_android: "assets/app_icons/ic_launcher.png"
  image_path_ios: "assets/app_icons/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/app_icons/ic_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/app_icons/ic_foreground.png" # only available for Android 8.0 devices and above

flutter:
  assets:
    - assets/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fira_sans_regular.ttf
          weight: 500
        - asset: assets/fira_sans_light.ttf
          weight: 200
  uses-material-design: true
