// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5wXut8qgbvEBlL01U370yNbTjRgWMIFk',
    appId: '1:648413487443:android:8568ccfe016e94430181a6',
    messagingSenderId: '648413487443',
    projectId: 'eye-helper-4ee78',
    databaseURL: 'https://eye-helper-4ee78.firebaseio.com',
    storageBucket: 'eye-helper-4ee78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlfqmzQbDYnedgpZGpzbHLeNbvMeEa3Vc',
    appId: '1:648413487443:ios:cfeea460b5b7a1d80181a6',
    messagingSenderId: '648413487443',
    projectId: 'eye-helper-4ee78',
    databaseURL: 'https://eye-helper-4ee78.firebaseio.com',
    storageBucket: 'eye-helper-4ee78.appspot.com',
    androidClientId: '648413487443-62s4h3sav93te5shqef2huo3hn5qsl18.apps.googleusercontent.com',
    iosClientId: '648413487443-hu95c5o1ile72ni4ltkur1feoug28qee.apps.googleusercontent.com',
    iosBundleId: 'com.fluttergods.eyehelperapp',
  );
}
